=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/coments.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT coments (comment)+>


<!ELEMENT comment (commentID,customerID,transactionID,locationID,
                   TruckID,CommentTime,comments)>

<!ELEMENT commentID (#PCDATA)>

<!ELEMENT customerID (#PCDATA)>

<!ELEMENT transactionID (#PCDATA)>

<!ELEMENT locationID (#PCDATA)>

<!ELEMENT TruckID (#PCDATA)>

<!ELEMENT CommentTime (#PCDATA)>

<!ELEMENT comments (#PCDATA)>
<!ATTLIST coments commentID CDATA #IMPLIED>

=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/comments.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE coments SYSTEM "coments.dtd">
<comments>
	<comment>
		<commentID>001</commentID>
		<customerID>1000</customerID>
		<transactionID>5000</transactionID>
		<locationID>60616</locationID>
		<TruckID>234323</TruckID>
		<CommentTime>1210</CommentTime>
		<comment_data>The service was good</comment_data>
	</comment>
	
	<comment>
		<commentID>002</commentID>
		<customerID>1001</customerID>
		<transactionID>5001</transactionID>
		<locationID>60616</locationID>
		<TruckID>987467</TruckID>
		<CommentTime>0800</CommentTime>
		<comment_data>The service must be improved</comment_data>
	</comment>
</comments>
