=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/employees.dtd
<?xml encoding="UTF-8"?>


<!ELEMENT employees (employee1,employee2,employee3,employee4,employee5,
                     employee6,employee7)>

<!ELEMENT employee1 (EmployeeID,Name,contact,Job_title,
                     SocialSecurityNumber,DriverLicenseNumber,Location,
                     Birthdate,DateHired,Salary,Notes)>

<!ELEMENT employee2 (EmployeeID,Name,contact,Job_title,
                     SocialSecurityNumber,DriverLicenseNumber,Location,
                     Birthdate,DateHired,Salary,Notes)>

<!ELEMENT employee3 (EmployeeID,Name,contact,Job_title,
                     SocialSecurityNumber,DriverLicenseNumber,Location,
                     Birthdate,DateHired,Salary,Notes)>

<!ELEMENT employee4 (EmployeeID,Name,contact,Job_title,
                     SocialSecurityNumber,DriverLicenseNumber,Location,
                     Birthdate,DateHired,Salary,Notes)>

<!ELEMENT employee5 (EmployeeID,Name,contact,Job_title,
                     SocialSecurityNumber,DriverLicenseNumber,Location,
                     Birthdate,DateHired,Salary,Notes)>

<!ELEMENT employee6 (EmployeeID,Name,contact,Job_title,
                     SocialSecurityNumber,DriverLicenseNumber,Location,
                     Birthdate,DateHired,Salary,Notes)>

<!ELEMENT employee7 (EmployeeID,Name,contact,Job_title,
                     SocialSecurityNumber,DriverLicenseNumber,Location,
                     Birthdate,DateHired,Salary,Notes)>

<!ELEMENT EmployeeID (#PCDATA)>

<!ELEMENT Name (FirstName,LastName)>

<!ELEMENT FirstName (#PCDATA)>

<!ELEMENT LastName (#PCDATA)>

<!ELEMENT contact (Email,Extension,HomePhone,CellPhone)>

<!ELEMENT Email (#PCDATA)>

<!ELEMENT Extension (#PCDATA)>

<!ELEMENT HomePhone (#PCDATA)>

<!ELEMENT CellPhone (#PCDATA)>

<!ELEMENT Job_title (#PCDATA)>

<!ELEMENT SocialSecurityNumber (#PCDATA)>

<!ELEMENT DriverLicenseNumber (#PCDATA)>

<!ELEMENT Location (Address,City,State,PostalCode)>

<!ELEMENT Address (#PCDATA)>

<!ELEMENT City (#PCDATA)>

<!ELEMENT State (#PCDATA)>

<!ELEMENT PostalCode (#PCDATA)>

<!ELEMENT Birthdate (#PCDATA)>

<!ELEMENT DateHired (#PCDATA)>

<!ELEMENT Salary (#PCDATA)>

<!ELEMENT Notes (#PCDATA)>
<!ATTLIST employees EmployeeID CDATA #IMPLIED>

=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/employees.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">
<employees>
	<employee>
		<EmployeeID>01</EmployeeID>
		<Name>
			<FirstName>Prasanna</FirstName>
			<LastName>singh</LastName>
		</Name>
		<contact>
			<Email>prasanna@gmail.com</Email>
			<Extension>+1</Extension>
			<HomePhone>1397787798</HomePhone>
			<CellPhone>1978887498</CellPhone>
		</contact>
		<Job_title>Manager</Job_title>
		<SocialSecurityNumber>99887766</SocialSecurityNumber>
		<DriverLicenseNumber>P98477388299</DriverLicenseNumber>
		<Location>
			<Address>400 E Randolph</Address>
			<City>chicago</City>
			<State>Illinois</State>
			<PostalCode>60616</PostalCode>
		</Location>
		<Birthdate>1985-10-02</Birthdate>
		<DateHired>2016-03-11</DateHired>
		<Salary>40000</Salary>
		<Notes>Morning shift</Notes>
	</employee>
	
	
	<employee>
		<EmployeeID>22</EmployeeID>
		<Name>
			<FirstName>Adhitya</FirstName>
			<LastName>taunk</LastName>
		</Name>
		<contact>
			<Email>adhitya@gmail.com</Email>
			<Extension>+1</Extension>
			<HomePhone>1493847783</HomePhone>
			<CellPhone>1984039488</CellPhone>
		</contact>
		<Job_title>Driver</Job_title>
		<SocialSecurityNumber>88399483</SocialSecurityNumber>
		<DriverLicenseNumber>P99477384990</DriverLicenseNumber>
		<Location>
			<Address>600 E Madison</Address>
			<City>chicago</City>
			<State>Illinois</State>
			<PostalCode>60616</PostalCode>
		</Location>
		<Birthdate>1987-11-23</Birthdate>
		<DateHired>2015-08-12</DateHired>
		<Salary>30000</Salary>
		<Notes>Evening shift</Notes>
	</employee>
	
	
	
	<employee>
		<EmployeeID>98</EmployeeID>
		<Name>
			<FirstName>James</FirstName>
			<LastName>Thomas</LastName>
		</Name>
		<contact>
			<Email>james@gmail.com</Email>
			<Extension>+1</Extension>
			<HomePhone>1483700222</HomePhone>
			<CellPhone>2128948398</CellPhone>
		</contact>
		<Job_title>Manager</Job_title>
		<SocialSecurityNumber>883920092</SocialSecurityNumber>
		<DriverLicenseNumber>T883928837488</DriverLicenseNumber>
		<Location>
			<Address>700 E Madison</Address>
			<City>San diego</City>
			<State>California</State>
			<PostalCode>662789</PostalCode>
		</Location>
		<Birthdate>1983-12-01</Birthdate>
		<DateHired>2016-02-05</DateHired>
		<Salary>45000</Salary>
		<Notes></Notes>
	</employee>
	
	
	<employee>
		<EmployeeID>44</EmployeeID>
		<Name>
			<FirstName>Mike</FirstName>
			<LastName>daniel</LastName>
		</Name>
		<contact>
			<Email>mike@gmail.com</Email>
			<Extension>+1</Extension>
			<HomePhone>2147399847</HomePhone>
			<CellPhone>1129938477</CellPhone>
		</contact>
		<Job_title>Manager</Job_title>
		<SocialSecurityNumber>1239284758</SocialSecurityNumber>
		<DriverLicenseNumber>YY8837288394</DriverLicenseNumber>
		<Location>
			<Address>800 E Madison</Address>
			<City>Los Angeles </City>
			<State>California</State>
			<PostalCode>993823</PostalCode>
		</Location>
		<Birthdate>1989-06-11</Birthdate>
		<DateHired>2017-08-07</DateHired>
		<Salary>45000</Salary>
		<Notes></Notes>
	</employee>
	
	<employee>
		<EmployeeID>70</EmployeeID>
		<Name>
			<FirstName>Jackson</FirstName>
			<LastName>carlson</LastName>
		</Name>
		<contact>
			<Email>jackson@gmail.com</Email>
			<Extension>+1</Extension>
			<HomePhone>1372773849</HomePhone>
			<CellPhone>2129948783</CellPhone>
		</contact>
		<Job_title>Manager</Job_title>
		<SocialSecurityNumber>884739993</SocialSecurityNumber>
		<DriverLicenseNumber>UI88392887738</DriverLicenseNumber>
		<Location>
			<Address>900 E Madison</Address>
			<City>New York </City>
			<State>New York</State>
			<PostalCode>229384</PostalCode>
		</Location>
		<Birthdate>1991-06-11</Birthdate>
		<DateHired>2017-08-10</DateHired>
		<Salary>45000</Salary>
		<Notes></Notes>
	</employee>
	
	<employee>
		<EmployeeID>49</EmployeeID>
		<Name>
			<FirstName>Kiesil</FirstName>
			<LastName>Johnson</LastName>
		</Name>
		<contact>
			<Email>kiesil@gmail.com</Email>
			<Extension>+1</Extension>
			<HomePhone>1338499383</HomePhone>
			<CellPhone>2099384999</CellPhone>
		</contact>
		<Job_title>Manager</Job_title>
		<SocialSecurityNumber>399894832</SocialSecurityNumber>
		<DriverLicenseNumber>HO883729983</DriverLicenseNumber>
		<Location>
			<Address>2901 South drive</Address>
			<City>Houston </City>
			<State>Texas</State>
			<PostalCode>993827</PostalCode>
		</Location>
		<Birthdate>1983-04-29</Birthdate>
		<DateHired>2012-11-01</DateHired>
		<Salary>45000</Salary>
		<Notes></Notes>
	</employee>
	
	<employee>
		<EmployeeID>09</EmployeeID>
		<Name>
			<FirstName>Ricardo</FirstName>
			<LastName>Doborra</LastName>
		</Name>
		<contact>
			<Email>ricardo@gmail.com</Email>
			<Extension>+1</Extension>
			<HomePhone>1284788299</HomePhone>
			<CellPhone>2143748898</CellPhone>
		</contact>
		<Job_title>Manager</Job_title>
		<SocialSecurityNumber>22938477</SocialSecurityNumber>
		<DriverLicenseNumber>R9938299938</DriverLicenseNumber>
		<Location>
			<Address>2801 South drive</Address>
			<City>Phoenix </City>
			<State>Arizona</State>
			<PostalCode>776655</PostalCode>
		</Location>
		<Birthdate>1985-02-18</Birthdate>
		<DateHired>2005-09-12</DateHired>
		<Salary>45000</Salary>
		<Notes></Notes>
	</employee>
	
</employees>
