=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/expense.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT expense (expense1,expense2)>

<!ELEMENT expense1 (ExpenseID,EmployeeID,ExpenseType,PurposeofExpense,
                    AmountSpent,Description,DatePurchased,DateSubmitted,
                    AdvanceAmount,PaymentMethod)>

<!ELEMENT expense2 (ExpenseID,EmployeeID,ExpenseType,PurposeofExpense,
                    AmountSpent,Description,DatePurchased,DateSubmitted,
                    AdvanceAmount,PaymentMethod)>

<!ELEMENT ExpenseID (#PCDATA)>

<!ELEMENT EmployeeID (#PCDATA)>

<!ELEMENT ExpenseType (#PCDATA)>

<!ELEMENT PurposeofExpense (#PCDATA)>

<!ELEMENT AmountSpent (#PCDATA)>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT DatePurchased (#PCDATA)>

<!ELEMENT DateSubmitted (#PCDATA)>

<!ELEMENT AdvanceAmount (#PCDATA)>

<!ELEMENT PaymentMethod (#PCDATA)>
<!ATTLIST expense ExpenseID CDATA #IMPLIED>

=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/expenses.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE expense SYSTEM "expense.dtd">
<expense>
	<expense>
		<ExpenseID>2556</ExpenseID>
		<EmployeeID>02</EmployeeID>
		<ExpenseType>Employee</ExpenseType>
		<PurposeofExpense>Delivery</PurposeofExpense>
		<AmountSpent>30$</AmountSpent>
		<Description>Amount spent on food during delivery of cars</Description>
		<DatePurchased>10-03-2016</DatePurchased>
		<DateSubmitted>10-09-2016</DateSubmitted>
		<AdvanceAmount>0</AdvanceAmount>
		<PaymentMethod>cash</PaymentMethod>
	</expense>		
	
	<expense>
		<ExpenseID>3102</ExpenseID>
		<EmployeeID>01</EmployeeID>
		<ExpenseType>Truck Insurance</ExpenseType>
		<PurposeofExpense>Weekend work</PurposeofExpense>
		<AmountSpent>60$</AmountSpent>
		<Description>Basic pay for working on weekend</Description>
		<DatePurchased></DatePurchased>
		<DateSubmitted>12-01-2016</DateSubmitted>
		<AdvanceAmount>20</AdvanceAmount>
		<PaymentMethod>cash</PaymentMethod>
	</expense>
	
</expense>
