=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/transactions.dtd
<?xml encoding="UTF-8"?>


<!ELEMENT transactions (transaction1,transaction2,transaction3,
                        transaction4)>

<!ELEMENT transaction1 (transactionID,OrderID,priceID,employeeID,
                        transactionDate,transactionDescription,
                        transactionAmount,truck_detail,car_details,
                        quantity,Price_estimate,special)>

<!ELEMENT transaction2 (transactionID,OrderID,priceID,employeeID,
                        transactionDate,transactionDescription,
                        transactionAmount,truck_detail,car_details,
                        quantity,Price_estimate,special)>

<!ELEMENT transaction3 (transactionID,OrderID,priceID,employeeID,
                        transactionDate,transactionDescription,
                        transactionAmount,truck_detail,car_details,
                        quantity,Price_estimate,special)>

<!ELEMENT transaction4 (transactionID,OrderID,priceID,employeeID,
                        transactionDate,transactionDescription,
                        transactionAmount,truck_detail,car_details,
                        quantity,Price_estimate,special)>

<!ELEMENT transactionID (#PCDATA)>

<!ELEMENT OrderID (#PCDATA)>

<!ELEMENT priceID (#PCDATA)>

<!ELEMENT employeeID (#PCDATA)>

<!ELEMENT transactionDate (#PCDATA)>

<!ELEMENT transactionDescription (#PCDATA)>

<!ELEMENT transactionAmount (#PCDATA)>

<!ELEMENT truck_detail (TruckID,truckNo)>

<!ELEMENT TruckID (#PCDATA)>

<!ELEMENT truckNo (#PCDATA)>

<!ELEMENT car_details (make,model,year,VIN,runNumber)>

<!ELEMENT make (#PCDATA)>

<!ELEMENT model (#PCDATA)>

<!ELEMENT year (#PCDATA)>

<!ELEMENT VIN (#PCDATA)>

<!ELEMENT runNumber (#PCDATA)>

<!ELEMENT quantity (#PCDATA)>

<!ELEMENT Price_estimate (discount,unitPrice,driverPrice,rate,
                          surcharge)>

<!ELEMENT discount (#PCDATA)>

<!ELEMENT unitPrice (#PCDATA)>

<!ELEMENT driverPrice (#PCDATA)>

<!ELEMENT rate (#PCDATA)>

<!ELEMENT surcharge (#PCDATA)>

<!ELEMENT special (#PCDATA)>
<!ATTLIST transactions transactionID CDATA #IMPLIED>

=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/transactions.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE transactions SYSTEM "transactions.dtd">
<transactions>
	<transaction>
		<transactionID>T001</transactionID>
		<OrderID>OR001</OrderID> 
		<priceID>001</priceID>
		<employeeID>01</employeeID>
		<transactionDate>10-02-2016</transactionDate>
		<transactionDescription>Car transferred from chicago to Las Angeles</transactionDescription>
		<transactionAmount>1500</transactionAmount>
		<truck_detail>
			<TruckID>9983</TruckID>
			<truckNo>HY2291</truckNo>
		</truck_detail>
		<car_details>					
			<make>Toyota</make>
			<model>corolla</model>
			<year>2016</year>
			<VIN>1HGBH41JXMN109187</VIN>
			<runNumber>34333200</runNumber>
		</car_details>
		<quantity>1</quantity>
		<Price_estimate>
			<discount>200</discount>
			<unitPrice>1200</unitPrice>
			<driverPrice>400</driverPrice>
			<rate>0</rate>
			<surcharge>100</surcharge>
		</Price_estimate>
		<special>No</special>
	</transaction>
	
	<transaction>
		<transactionID>T002</transactionID>
		<OrderID>OR001</OrderID> 
		<priceID>002</priceID>
		<employeeID>01</employeeID>
		<transactionDate>10-02-2016</transactionDate>
		<transactionDescription>Car transferred from chicago to New York</transactionDescription>
		<transactionAmount>5000</transactionAmount>
		<truck_detail>
			<TruckID>9983</TruckID>
			<truckNo>HY2291</truckNo>
		</truck_detail>
		<car_details>					
			<make>Toyota</make>
			<model>corolla</model>
			<year>2016</year>
			<VIN>1HGBH41JXMN109187</VIN>
			<runNumber>34333200</runNumber>
		</car_details>
		<quantity>1</quantity>
		<Price_estimate>
			<discount>0</discount>
			<unitPrice>4000</unitPrice>
			<driverPrice>800</driverPrice>
			<rate>0</rate>
			<surcharge>200</surcharge>
		</Price_estimate>
		<special>No</special>
	</transaction>

	<transaction>
		<transactionID>T003</transactionID>
		<OrderID>OR001</OrderID>
		<priceID>003</priceID>
		<employeeID>9</employeeID>
		<transactionDate>01-15-2017</transactionDate>
		<transactionDescription>Car transferred from phoenix to San diego</transactionDescription>
		<transactionAmount>2700</transactionAmount>
		<truck_detail>
			<TruckID>0091</TruckID>
			<truckNo>IC0091</truckNo>
		</truck_detail>
		<car_details>					
			<make>Honda</make>
			<model>CRV</model>
			<year>2015</year>
			<VIN>1HGBH41JXMN109186</VIN>
			<runNumber>99888374</runNumber>
		</car_details>
		<quantity>1</quantity>
		<Price_estimate>
			<discount>200</discount>
			<unitPrice>2200</unitPrice>
			<driverPrice>500</driverPrice>
			<rate>0</rate>
			<surcharge>200</surcharge>
		</Price_estimate>
		<special>No</special>
	</transaction>	
	
	<transaction>
		<transactionID>T004</transactionID>
		<OrderID>OR001</OrderID>
		<priceID>004</priceID>
		<employeeID>9</employeeID>
		<transactionDate>03-30-2017</transactionDate>
		<transactionDescription>Car transferred from phoenix to chicago</transactionDescription>
		<transactionAmount>3000</transactionAmount>
		<truck_detail>
			<TruckID>0091</TruckID>
			<truckNo>IC0091</truckNo>
		</truck_detail>
		<car_details>					
			<make>Audi</make>
			<model>A6</model>
			<year>2015</year>
			<VIN>1HGBH41JXMN109186</VIN>
			<runNumber>99837288</runNumber>
		</car_details>
		<quantity>1</quantity>
		<Price_estimate>
			<discount>0</discount>
			<unitPrice>2200</unitPrice>
			<driverPrice>500</driverPrice>
			<rate>0</rate>
			<surcharge>300</surcharge>
		</Price_estimate>
		<special>No</special>
	</transaction>
	
</transactions>
