=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/trucks.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Trucks (truck1,truck2)>


<!ELEMENT truck1 (TruckID,TruckNo,Truckdesc,LicensePlateNo,VIN)>

<!ELEMENT truck2 (TruckID,TruckNo,Truckdesc,LicensePlateNo,VIN)>

<!ELEMENT TruckID (#PCDATA)>

<!ELEMENT TruckNo (#PCDATA)>

<!ELEMENT Truckdesc (Make,Year,Model,Color)>

<!ELEMENT Make (#PCDATA)>

<!ELEMENT Year (#PCDATA)>

<!ELEMENT Model (#PCDATA)>

<!ELEMENT Color (#PCDATA)>

<!ELEMENT LicensePlateNo (#PCDATA)>

<!ELEMENT VIN (#PCDATA)>
<!ATTLIST Trucks TruckID CDATA #IMPLIED>

=== mpradeep1994/Personal-medical-Application/code/src/parser/xml/trucks.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE Trucks SYSTEM "trucks.dtd">
<Trucks>
	<truck> 
		<TruckID>0091</TruckID>
		<TruckNo>IC0091</TruckNo>
		<!--EmployeeID>22</EmployeeID-->
		<Truckdesc>
			<Make>Benz</Make>
			<Year>2012</Year>
			<Model>Cruze</Model>
			<Color>Red</Color>
		</Truckdesc>
		<LicensePlateNo>IC0091</LicensePlateNo>
		<VIN>1HGBH41JXMN109186</VIN>
	</truck>
	
	<truck> 
		<TruckID>9983</TruckID>
		<TruckNo>HY2291</TruckNo>
		<!--EmployeeID>22</EmployeeID-->
		<Truckdesc>
			<Make>Benz</Make>
			<Year>2016</Year>
			<Model>corz</Model>
			<Color>Black</Color>
		</Truckdesc>
		<LicensePlateNo>PY9983</LicensePlateNo>
		<VIN>1HGBH41JXMN109187</VIN>
	</truck>
</Trucks>
